// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/wechat/mp.proto

package wechat

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_a491b14375d80f52, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type Token struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Valid                bool     `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	Errors               []*Error `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_a491b14375d80f52, []int{1}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Token) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *Token) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_a491b14375d80f52, []int{2}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "wechat.Request")
	proto.RegisterType((*Token)(nil), "wechat.Token")
	proto.RegisterType((*Error)(nil), "wechat.Error")
}

func init() { proto.RegisterFile("proto/wechat/mp.proto", fileDescriptor_a491b14375d80f52) }

var fileDescriptor_a491b14375d80f52 = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x4f, 0x4d, 0xce, 0x48, 0x2c, 0xd1, 0xcf, 0x2d, 0xd0, 0x03, 0xf3, 0x85, 0xd8,
	0x20, 0x02, 0x4a, 0xb2, 0x5c, 0xec, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x42, 0x5c,
	0x2c, 0xc9, 0xf9, 0x29, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x52, 0x14,
	0x17, 0x6b, 0x48, 0x7e, 0x76, 0x6a, 0x9e, 0x90, 0x08, 0x17, 0x6b, 0x09, 0x88, 0x01, 0x95, 0x85,
	0x70, 0x40, 0xa2, 0x65, 0x89, 0x39, 0x99, 0x29, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x1c, 0x41, 0x10,
	0x8e, 0x90, 0x2a, 0x17, 0x5b, 0x6a, 0x51, 0x51, 0x7e, 0x51, 0xb1, 0x04, 0xb3, 0x02, 0xb3, 0x06,
	0xb7, 0x11, 0xaf, 0x1e, 0xc4, 0x32, 0x3d, 0x57, 0x90, 0x68, 0x10, 0x54, 0x52, 0xc9, 0x96, 0x8b,
	0x15, 0x2c, 0x80, 0x62, 0x31, 0x2b, 0xc4, 0x62, 0x21, 0x05, 0x2e, 0xee, 0x94, 0xd4, 0xe2, 0xe4,
	0xa2, 0xcc, 0x82, 0x92, 0xcc, 0xfc, 0x3c, 0xb0, 0xf9, 0x9c, 0x41, 0xc8, 0x42, 0x46, 0x26, 0x5c,
	0x1c, 0xbe, 0x05, 0xe1, 0x60, 0x83, 0x85, 0x34, 0xb8, 0x58, 0x1c, 0x4b, 0x4b, 0x32, 0x84, 0xf8,
	0x61, 0x36, 0x41, 0xfd, 0x24, 0x05, 0xb7, 0x1a, 0xec, 0x0b, 0x25, 0x86, 0x24, 0x36, 0xb0, 0xf7,
	0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x9d, 0x81, 0x44, 0x04, 0x17, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for MpWechat service

type MpWechatClient interface {
	// 用户验证授权
	Auth(ctx context.Context, in *Request, opts ...client.CallOption) (*Token, error)
}

type mpWechatClient struct {
	c           client.Client
	serviceName string
}

func NewMpWechatClient(serviceName string, c client.Client) MpWechatClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "wechat"
	}
	return &mpWechatClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *mpWechatClient) Auth(ctx context.Context, in *Request, opts ...client.CallOption) (*Token, error) {
	req := c.c.NewRequest(c.serviceName, "MpWechat.Auth", in)
	out := new(Token)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MpWechat service

type MpWechatHandler interface {
	// 用户验证授权
	Auth(context.Context, *Request, *Token) error
}

func RegisterMpWechatHandler(s server.Server, hdlr MpWechatHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&MpWechat{hdlr}, opts...))
}

type MpWechat struct {
	MpWechatHandler
}

func (h *MpWechat) Auth(ctx context.Context, in *Request, out *Token) error {
	return h.MpWechatHandler.Auth(ctx, in, out)
}
